runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^node_modules$
- ^scss$
- ^.idea$

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(*.html)
  static_files: \1
  upload: (.*)

- url: /(*.txt)
  static_files: \1
  upload: (.*)

- url: /(*.xml)
  static_files: \1
  upload: (.*)

- url: /vendor/(.*)
  static_files: vendor/\1
  upload: vendor/(.*)

- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)
